name: Test callable action

on: [workflow_call]

jobs:
  echo_job:
   runs-on: ubuntu-latest

  strategy:
   matrix:
    name: [World, Galaxy, Kitchen ]

  steps:
    - run: echo Hello
    - run: echo ${{ name }}